name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run:  npm install

      - name: Run unit tests
        run: npm run test

      - name: Run the app
        run: npm run dev

      - name: Run integration tests
        run: npm run cypress:open
          